trigger:
- master

pr:
- master

pool:
  vmImage: 'macos-10.14'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: templates/yml/node/combo/npm-build-validation-xunit-cobertura.yml@templates
  parameters:
    publishTestResults:
      taskDisplayName: 'Publish unit test results'
      testResultsFormat: 'JUnit'
      testResultsFiles: 'xunit.xml'
      searchFolder: '$(Build.SourcesDirectory)/.testresults/unit'
      testRunTitle: 'get-package-version::Unit Tests::Mac PR - Build $(Build.BuildId)'
